config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:create, :new] do
    resources :comments, only: [:create]
    resources :likes, only: :create do
      collection do
        delete :destroy
      end
    end
  end
  devise_for :users
  root "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes
  has_many :comments

  validates :username, presence: true

  def like!(post)
    likes << Like.new(post: post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_params, if: :devise_controller?

  protected

    def configure_permitted_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new; end

  def create
    @post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.post = @post
    comment.user = current_user

    if comment.save
    else
      render :new, statis: :unprocessable_entity
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.like!(@post)
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:post_id])
    current_user.likes.where(post_id: @post.id).delete_all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    if @post.valid?
      @post.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    def index;
      @posts = Post.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: post_comments_path(post), class: "comment-form"  do |f| %>
  <%= f.text_field :body %>
  <%= f.submit :post %>  
<% end %>

app/views/comments/_list.html.erb
<%= post.comments.each do |comment| %>
  <div class="comment">
    <span class="comment-author"><%= comment.user.username %></span>
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "comment-form" do %>
  <%= render partial: "comments/form", locals: { post: @post } %>
<% end %>

<%= turbo_stream.update "post-comments-list" do %>
  <%= render partial: "comments/list", locals: { post: @post } %>
<% end %>

<%= turbo_stream.update "post-comments-count" do %>
  <%= pluralize(@post.comments.count, "comment") %>
<% end %>

app/views/comments/new.turbo_stream.erb
<%= turbo_stream.update "comment-form" do %>
  <%= render partial: "comments/form", locals: { post: @post } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="nav">
      <% if user_signed_in? %>
        <%= turbo_frame_tag "post-form" do %>
          <%= link_to "New Post", new_post_path %>
        <% end %>
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<%= turbo_frame_tag "post-likes" do %>
  <%= button_to "", post_likes_path(@post), class: "post-actions-unlike", method: :delete %>
<% end %>

app/views/likes/destroy.html.erb
<%= turbo_frame_tag "post-likes" do %>
  <%= button_to "", post_likes_path(@post), class: "post-actions-like" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-author">
    <div class="avatar avatar-<%= rand(1..27) %>"></div>
    <div><%= post.user.username %></div>
  </div>
  <div class="post-body">
    <span><%= post.body %></span>
  </div>
  <div class="post-actions">
    <%= turbo_frame_tag "post-likes" do %>
      <%= button_to "", post_likes_path(post), class: "post-actions-like" %>
    <% end %>
    <div class="post-actions-comments" id="post-comments-count"><%= pluralize(post.comments.count, "comment") %></div>
  </div>
  <div class="post-comments">
    <div id="comment-form" ><%= render partial: "comments/form", locals: { post: post } %></div>
    <div id="post-comments-list">
      <%= render partial: "comments/list", locals: { post: post } %>
    </div>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <% render partial: "post", locals: { post: @post } %>
<% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag "post-form" do %>
  <%= form_with model: @post do |f| %>
    <%= f.text_field :body %>
    <%= f.submit :send %>
  <% end %>
<% end %>

app/views/site/index.html.erb
Welcome

<div id="posts">
  <%= render @posts %>
</div>